# Generated by Django 3.2.10 on 2022-04-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220422_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
