# Generated by Django 3.2.10 on 2022-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
    ]
