# Generated by Django 3.2.10 on 2022-04-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_orders_deliver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='user_id',
        ),
    ]
